### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ogomez92** [nicross/auraboros#2]
Hi. I have created a mac build.
It's not notarized yet, but I can try to do it I guess. I have a developer account.
Let me know  if you are interested.

**Comment by nicross** [comment]
Hi! I'm beginning to plan a post-jam update. That could be a good opportunity to distribute one. I'll reach out when it's ready.

**Comment by nicross** [comment]
Slight change of plans for me. Thanks @ogomez92 for providing a macOS build, now available on the [Auraboros itch.io page](https://shiftbacktick.itch.io/auraboros)!
